### ISSUE TITLE
How to work with class based views?

### ISSUE THREAD

**Issue by BoPeng** [idlesign/django-xross#2]
In the documentation `@xross_view` is added to a function based view.

```
@xross_view(list_news)  # Decorate your view - instruct xross to use `list_news` when needed.
def index_page(request):
   ...
```

My view is actually very complex and need `xross` just for two tiny elements (bookmark and star). I suppose I can render the rest of the items regularly, leaving the two buttons blank and let `xross` fill the content. However, how do I add `@xross_view` to my generic view?

```
class MyView(generic.DetailView):
    ...
```

**Comment by idlesign** [comment]
There should be no difference for class-based views: you decorate the actual working method (`get()` in most cases). See an example: https://github.com/idlesign/pythonz/blob/master/pythonz/apps/generics/views.py#L360

**Comment by BoPeng** [comment]
I am using "generic" detailed view for which I only define functions such as `get_context_data`, `get_object` (see https://docs.djangoproject.com/en/3.0/topics/class-based-views/generic-display/). Perhaps I can do something like

```
@xross_view(list_news)
def get(self, *args, **kwargs):
    super(myview, self).get(*args, **kwargs)
```
to just inject the decorator?

**Comment by idlesign** [comment]
Sure, give it a try. Do not forget `return`.

**Comment by BoPeng** [comment]
Thanks, the version that works for me is

```
   @xross_view(toggle_bookmark, toggle_star)
   def get(self, request, *args, **kwargs):
       xross_listener(item=self.get_object())
       return super(ItemView, self).get(request, *args, **kwargs)
```
