### ISSUE TITLE
Using intercooler.js for AJAX calls

### ISSUE THREAD

**Issue by BoPeng** [idlesign/django-xross#3]
@idlesign You mentioned in [another post](https://github.com/idlesign/django-siteflags/issues/6#issuecomment-597513226) that

> django-xross is a bit old and it's JS needs a refresher, but it works for me.

I came across [`intercooler.js`](https://intercoolerjs.org/) today which seems to be doing the same thing as the JS part of `django-xross` is doing. Is it possible for you to make use of `intercooler.js` if it is a more mature and well-supported project?

Disclaimer: I am bad at JS and is not at a position to judge the quality of `intercooler.js` and/or the JS part of `django-xross`.

Edit: There is an existing project called [django-intercoolerjs](https://github.com/brejoc/django-intercoolerjs), which is a simple wrapper that adds the js. `django-xross` has doing a lot more than it.

**Comment by idlesign** [comment]
`intercoolerjs` looks similar indeed. Thank you.
An interesting thing is that `intercoolerjs` and `xross` have started  almost at the same time. So I would say, that `intercoolerjs` JS is almost equally old %)

Besides the notation difference,  I see no `actions` support in `intercoolerjs`, also it requires passing URLs. So there's no easy way switching to it: either we ruin backward compatibility, or making an sophisticated adapter.

> There is an existing project called django-intercoolerjs, which is a simple wrapper that adds the js. django-xross has doing a lot more than it.

I'd not call it a wrapper, rather a very simple demo. It certainly may do better providing integration.

**Comment by BoPeng** [comment]
I ended up switching to `intercooler.js` and [`django-intercoolerjs-helper`](https://github.com/kezabelle/django-intercoolerjs-helpers) (which is not needed), not because it is better than `xross` for frontend/backend communication, but because it provides more functions. For example, it allows me to change my hand written `error` disappearing JS code with 

```
class="error"  ic-trigger-on="mouseover" ic-action="fadeOut:1000;remove"
```
and adding some other small AJAX functions here and there. Then it does not make much sense to use two similar pieces of JS code in the project.

For the `xross` part, I ended up replacing the flag-switching code with something like

```html
<form id='toggle-star'>
    {{ csrf_input }}
    {% if request.user.is_authenticated %}
    {% if workflow.is_flagged(request.user, workflow.FLAGS['starred']) %}
    <button  ic-post-to="{{ request.path }}"  ic-target='#toggle-star'
      class="xross btn btn-light border-0"   id='star-yes'>
    <i class="fas fa-star fa-fw"></i>
    {% else %}
    <button  ic-post-to="{{ request.path }}"  ic-target='#toggle-star'
      class="xross btn btn-light border-0"  id="star-no" >
    <i class="far fa-star fa-fw"></i>
    {% endif %} {% else %}
    <button class="xross btn btn-light" disabled>
    <i class="far fa-star fa-fw"></i>
    {% endif %}

    <span class="badge badge-light">{{ workflow.flag_count('starred') }}</span>
  </button>
</form>
```

for the frontend  (I am using jinja2 template engine), and

```python
    def post(self, request, *args, **kwargs):
        # handle partial update sent from intercooler
        wf = self.get_object()
        if request.intercooler_data.trigger.id == 'star-yes':
            wf.remove_flag(request.user, status=Workflow.FLAGS['starred'])            
        else:
            wf.set_flag(request.user, status=Workflow.FLAGS['starred'])
        return render(request, 'parts/star.html', {'workflow': wf})
```
for the backend. Note that I used `POST` and `csrf` because `GET` is not recommended for model changing actions. More importantly, it allowed me to use `def post` directly because I am using a `generic.DetailedView` so adding `post` does not interfere with any other code. The code is arguably easier to understand than the `xross` version.

**Comment by idlesign** [comment]
`xross` is now deperected, you may be interested in https://github.com/idlesign/django-siteajax though, since it uses `htmx`.
